name: Build Watch App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Create Config.xcconfig
      run: |
        echo "API_PASSWORD = SOME_PASSWORD" > Config.xcconfig
        echo "API_URL = SOME_URL" >> Config.xcconfig

    - name: Build
      run: |
        xcodebuild build \
          -project MininSchedule.xcodeproj \
          -scheme "MininSchedule Watch App" \
          -destination 'generic/platform=watchOS Simulator' \
          -configuration Release \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
